CLASS ycl_abapgit_repo_offline DEFINITION
  PUBLIC
  INHERITING FROM ycl_abapgit_repo
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS YCL_ABAPGIT_REPO_OFFLINE IMPLEMENTATION.
ENDCLASS.
