CLASS ycx_abapgit_cancel DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ycx_abapgit_cancel IMPLEMENTATION.
ENDCLASS.
